### ISSUE TITLE
How can i use lucaprot on paired rna seq data?

### ISSUE THREAD

**Issue by sirrgang** [alibaba/LucaProt#46]
We want to identify novel viruses in our lab and discussing the usage of lucaprot as well. Do you have any guidance how to improve the output by converting the rna seq (short read illumina files) into protein sequences so it best works with luca?

Thanks alot.

**Comment by non-name-2020** [comment]
> We want to identify novel viruses in our lab and discussing the usage of lucaprot as well. Do you have any guidance how to improve the output by converting the rna seq (short read illumina files) into protein sequences so it best works with luca?
> 
> Thanks alot.

Hi，@sirrgang

We typically use ORFfinde to translate RNA viral genomes. It is recommended that reads be assembled into contigs before ORFfinder is used to translate contigs into proteins. Direct use of reads for protein translation is not recommended.

Good Luck.
