### ISSUE TITLE
Is there any option to run in multiple threads?

### ISSUE THREAD

**Issue by permia** [alibaba/LucaProt#68]
I used the following commond without GPU. But it's slow. Is there any option to run in multiple threads?

```
python predict_many_samples.py \
	--fasta_file "$fasta"  \
	--save_file "${dir}"/"$name"_lucaprot_result.csv  \
	--emb_dir "${dir}"/emb/  \
	--truncation_seq_length 4096  \
	--dataset_name rdrp_40_extend  \
	--dataset_type protein     \
	--task_type binary_class     \
	--model_type sefn     \
	--time_str 20230201140320   \
	--step 100000  \
	--threshold 0.5 \
	--print_per_number 10 \
	--gpu_id -1


```

**Comment by permia** [comment]
Thanks for your reply.

**Comment by AlenaYoung** [comment]
> > I used the following commond without GPU. But it's slow. Is there any option to run in multiple threads?
> > ```
> > python predict_many_samples.py \
> > 	--fasta_file "$fasta"  \
> > 	--save_file "${dir}"/"$name"_lucaprot_result.csv  \
> > 	--emb_dir "${dir}"/emb/  \
> > 	--truncation_seq_length 4096  \
> > 	--dataset_name rdrp_40_extend  \
> > 	--dataset_type protein     \
> > 	--task_type binary_class     \
> > 	--model_type sefn     \
> > 	--time_str 20230201140320   \
> > 	--step 100000  \
> > 	--threshold 0.5 \
> > 	--print_per_number 10 \
> > 	--gpu_id -1
> > ```
> 
> You can split your fasta file into multi-files, and run this command for each split file.

您好，请问一下predict_many_samples.py会自动调用多线程运行程序（在我们的服务器上约90个CPU），如果把fasta序列拆成多个小的序列进行预测，分别跑predict_many_samples.py会更快一点么？
我们的蛋白序列约2w条，拆成4k条序列用90的线程跑还没跑完，这个速度正常吗感觉有点太慢了。如果log文件里的
```
done : 10
done : 20
```
指的是已完成的序列数目的话目前只跑完了1.5k条
`done : 1510`

**Comment by non-name-2020** [comment]
这个代码本身不会多线程，都是单线程一条一条，如果要多线程，你可以把你的fasta分为多个文件，每个文件调用一次，记得保存到不同的结果文件，最后合并结果

10294887346 ***@***.***>于2025年3月19日 周三23:08写道：

**Comment by AlenaYoung** [comment]
> 这个代码本身不会多线程，都是单线程一条一条，如果要多线程，你可以把你的fasta分为多个文件，每个文件调用一次，记得保存到不同的结果文件，最后合并结果
> 
> 10294887346 ***@***.***>于2025年3月19日 周三23:08写道：
> […](#)

感谢回复！
关于“这个代码本身不会多线程，都是单线程一条一条”但是在服务器上用top看这个python程序占用了90个CPU您清楚是什么问题吗，具体运行脚本如下：
```
python predict_many_samples.py \
> --fasta_file ${path}/${i}-protein.fasta  \
> --save_file ${outputpath}/${i}_result.csv  \
> --emb_dir ${outputpath}/${i}_emb/   \
> --truncation_seq_length 4096  \
> --dataset_name rdrp_40_extend  \
> --dataset_type protein     \
> --task_type binary_class     \
> --model_type sefn     \
> --time_str 20230201140320   \
> --step 100000  \
> --threshold 0.5 \
> --print_per_number 10 \
> --gpu_id -1
> done
```
我尝试了一下用seqkit split把${i}-protein.fasta分成了90个约400条序列的fasta文件，用nohup挂后台并行运行90条python代码，但是服务器一下子就被拉爆了，我们的服务器约有200个核，请问是不是说明这条python程序不是单线程的呢还是？
在log文件中也显示OpenBLAS blas_thread_init报错
