### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by dailypartita** [alibaba/LucaProt#75]
# RuntimeError while attempting to load the esm2_t36_3B_UR50D model

I encountered a RuntimeError while attempting to load the esm2_t36_3B_UR50D model in my environment. The error suggests that the zip archive is corrupted or incomplete. Below is the detailed traceback and environment information.
Do I need to manually re-download the 1-100.pt file for the esm2_t36_3B_UR50D model? Is there a known issue with this specific file being corrupted or incomplete?

PyTorch version: 1.13.1+cu117
Python version: Python 3.9.13
CUDA version: 11.7

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/e0a559af-8ca5-44a1-add7-030cfe70c9a3">

**Comment by non-name-2020** [comment]
> # RuntimeError while attempting to load the esm2_t36_3B_UR50D model
> I encountered a RuntimeError while attempting to load the esm2_t36_3B_UR50D model in my environment. The error suggests that the zip archive is corrupted or incomplete. Below is the detailed traceback and environment information. Do I need to manually re-download the 1-100.pt file for the esm2_t36_3B_UR50D model? Is there a known issue with this specific file being corrupted or incomplete?
> 
> PyTorch version: 1.13.1+cu117 Python version: Python 3.9.13 CUDA version: 11.7
> 
> <img alt="image" width="1334" src="https://private-user-images.githubusercontent.com/53904580/383891019-e0a559af-8ca5-44a1-add7-030cfe70c9a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMjk2MTIsIm5iZiI6MTczMTAyOTMxMiwicGF0aCI6Ii81MzkwNDU4MC8zODM4OTEwMTktZTBhNTU5YWYtOGNhNS00NGExLWFkZDctMDMwY2ZlNzBjOWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDAxMjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlN2QyNGI1NjllZjlhZjNhYmY3NWVjZDEwYjFmMzhhOWY4OTE0MDNjMGM3Mjg3OTVhMjUzZTg1MmUwMWZlNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yOf8DgiF80zYLfclxejthY6UP6DchQ3xgHg6Lh-gvhs">


This error message is caused by a failure to download the pre-trained large model(esm2), which may be a network issue.

You can manually download the `checkpoints /` from our FTP (http://47.93.21.181/esm2/) into the default directory: ~/.cache/torch/hub/, or your own directory (you need to download the latest code from GitHub and specify --torch_hub_dir as this directory when running the command for RdRP prediction).

**Comment by dailypartita** [comment]
After I re-downloaded the esm2_t36_3B_UR50D model, the script ran successfully. I appreciate your support!
