### ISSUE TITLE
如何从保存的checkpoint恢复训练？

### ISSUE THREAD

**Issue by inspirewind** [alibaba/LucaProt#77]

**Comment by non-name-2020** [comment]
我完善一下代码，写个step by step，让模型可以继续训练。最近一两周搞定。

Rui Li ***@***.***>于2024年11月21日 周四14:24写道：

**Comment by inspirewind** [comment]
可以提交PR吗？另外能否用torch.amp替换掉apex？

**Comment by non-name-2020** [comment]
可以pr。apex其实没有使用

Rui Li ***@***.***>于2024年11月21日 周四16:51写道：
