### ISSUE TITLE
关于LucaProt的安装问题

### ISSUE THREAD

**Issue by LucreceBorgia** [alibaba/LucaProt#79]
您好，想问一下在电脑上已经下载了Ubuntu 22.04.5 LTS和Python 3.9，点击README中的anaconda链接下载下来的SH文件是需要通过什么方式打开呢？我不是学计算机等相关专业的，电脑也是新换的，不知道是不是电脑里还缺什么软件，也不是很懂怎么安装依赖包。期待您的回复和帮助，谢谢！

**Comment by non-name-2020** [comment]
按照readme，一步一步来，先运行anaconda这个文件，进行安装anaconda，然后创建anaconda
的python39的虚拟环境，最后安装requirements.txt里面的依赖就可以运行lucaprot进行推理与预测了。

LucreceBorgia ***@***.***>于2024年12月5日 周四09:54写道：

**Comment by LucreceBorgia** [comment]
电脑提示选取一个应用以打开.sh文件，我应该使用什么应用来打开它？谢谢

**Comment by non-name-2020** [comment]
Linux （ubuntu）系统用终端命令行，./xxxx.sh 或者sh xxxx.sh

LucreceBorgia ***@***.***>于2024年12月5日 周四10:02写道：

**Comment by LucreceBorgia** [comment]
打开Ubuntu后页面显示的是：
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007019e
Error: 0x8007019e ??????? Linux ? Windows ????

Press any key to continue...

这是我少安装了什么软件吗？谢谢

**Comment by non-name-2020** [comment]
你这是个人的windowns电脑吧，你要找台linux的服务器，ubuntu的系统或者centos的系统

LucreceBorgia ***@***.***>于2024年12月5日 周四10:07写道：

**Comment by LucreceBorgia** [comment]
是个人的Windows电脑，您的意思是我这个设备并不适合运行LucaProt，需要换一个以Ubuntu或centos为系统的设备才可以运行LucaProt，我这样理解对吗？谢谢

**Comment by non-name-2020** [comment]
Windows按理也可以，只是我们没试过，不知道具体问题。建议这些都用Linux机器，包括ubuntu或者centos。

LucreceBorgia ***@***.***>于2024年12月5日 周四10:17写道：

**Comment by LucreceBorgia** [comment]
好的，我找个Linux的机器再试试。谢谢老师的耐心解答，之后有不懂之处还要请老师多多指导和帮助。再次感谢老师！
